### ISSUE TITLE
issue with status with xplayer

### ISSUE THREAD

**Issue by konrad50024** [ESX-Org/esx_status#1]
![screenshot_1](https://user-images.githubusercontent.com/19733453/30239201-0de705ba-954f-11e7-96af-e8765d1ba6ee.png)

**Comment by RomainLanz** [comment]
Hey @konrad50024! 👋 

1. What do you do to get this error?
2. Does all of your ESX resources are up to date?

**Comment by konrad50024** [comment]
I don't know what the issue is because I fixed it by just reinstalling everything
________________________________

**Comment by RomainLanz** [comment]
Cool!
