### ISSUE TITLE
Latest update broke esx_basicneeds

### ISSUE THREAD

**Issue by ForthtuN** [ESX-Org/esx_status#15]
Latest update of this seems to have broken esx_basicneeds. The bar doesen't show up anymore

**Comment by Malviaa** [comment]
> Latest update of this seems to have broken esx_basicneeds. The bar doesen't show up anymore

I have the same problem!

**Comment by Malviaa** [comment]
No one knows the solution for this?

**Comment by Malviaa** [comment]
> Hello, I have the same problem, here is the error
> https://www.allo-image.net/stockimg/upload/12817314185bded77961a3berroresx_status.jpg

you forgot to load the sql file to your db...................................................

**Comment by Malviaa** [comment]
> Latest update of this seems to have broken esx_basicneeds. The bar doesen't show up anymore

I just fixed the problem. I got older versions of esx_status and Basicneeds and it worked. Add me on discord an I can send you files Terion#0150

**Comment by radiodrag** [comment]
> > Latest update of this seems to have broken esx_basicneeds. The bar doesen't show up anymore
> 
> I just fixed the problem. I got older versions of esx_status and Basicneeds and it worked.

Which ones did you used?
