### ISSUE TITLE
big error ?

### ISSUE THREAD

**Issue by funzik** [ESX-Org/esx_status#2]
i have this error today with last updates all script esx 

[  78612875] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78612875] stack traceback:
[  78612890] 	server/main.lua:71: in upvalue 'handler'
[  78612890] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78612906] stack traceback:
[  78612906] 	[C]: in function 'error'
[  78612921] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78612921] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78622859] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78622859] stack traceback:
[  78622875] 	server/main.lua:71: in upvalue 'handler'
[  78622875] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78622890] stack traceback:
[  78622890] 	[C]: in function 'error'
[  78622906] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78622906] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78632890] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78632906] stack traceback:
[  78632906] 	server/main.lua:71: in upvalue 'handler'
[  78632921] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78632921] stack traceback:
[  78632937] 	[C]: in function 'error'
[  78632937] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78632937] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78642875] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78642890] stack traceback:
[  78642890] 	server/main.lua:71: in upvalue 'handler'
[  78642906] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78642906] stack traceback:
[  78642906] 	[C]: in function 'error'
[  78642921] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78642921] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78652890] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78652906] stack traceback:
[  78652906] 	server/main.lua:71: in upvalue 'handler'
[  78652921] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78652921] stack traceback:
[  78652937] 	[C]: in function 'error'
[  78652937] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78652953] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78662890] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78662890] stack traceback:
[  78662906] 	server/main.lua:71: in upvalue 'handler'
[  78662906] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78662921] stack traceback:
[  78662921] 	[C]: in function 'error'
[  78662937] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78662937] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78672921] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78672937] stack traceback:
[  78672953] 	server/main.lua:71: in upvalue 'handler'
[  78672953] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78672968] stack traceback:
[  78672968] 	[C]: in function 'error'
[  78672984] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78672984] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78682906] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78682921] stack traceback:
[  78682937] 	server/main.lua:71: in upvalue 'handler'
[  78682937] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78682953] stack traceback:
[  78682968] 	[C]: in function 'error'
[  78682968] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78682984] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78692687] Sending heartbeat to live-internal.fivem.net:30110
[  78692953] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78692968] stack traceback:
[  78692968] 	server/main.lua:71: in upvalue 'handler'
[  78692984] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78692984] stack traceback:
[  78693000] 	[C]: in function 'error'
[  78693015] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78693015] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78702953] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78702953] stack traceback:
[  78702968] 	server/main.lua:71: in upvalue 'handler'
[  78702968] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78702968] stack traceback:
[  78702984] 	[C]: in function 'error'
[  78702984] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78703000] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78712984] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78713000] stack traceback:
[  78713000] 	server/main.lua:71: in upvalue 'handler'
[  78713015] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78713015] stack traceback:
[  78713031] 	[C]: in function 'error'
[  78713031] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78713046] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78722968] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78722968] stack traceback:
[  78722984] 	server/main.lua:71: in upvalue 'handler'
[  78722984] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78723000] stack traceback:
[  78723000] 	[C]: in function 'error'
[  78723015] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78723015] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78733015] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78733015] stack traceback:
[  78733031] 	server/main.lua:71: in upvalue 'handler'
[  78733031] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78733046] stack traceback:
[  78733046] 	[C]: in function 'error'
[  78733062] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78733062] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78741468] Connecting: RENE POPULOS
[  78743000] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78743000] stack traceback:
[  78743015] 	server/main.lua:71: in upvalue 'handler'
[  78743015] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78743031] stack traceback:
[  78743031] 	[C]: in function 'error'
[  78743046] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78743046] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78745593] Sending heartbeat to live-internal.fivem.net:30110
[  78752968] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78752984] stack traceback:
[  78752984] 	server/main.lua:71: in upvalue 'handler'
[  78753000] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78753000] stack traceback:
[  78753015] 	[C]: in function 'error'
[  78753015] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78753031] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78763000] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78763015] stack traceback:
[  78763015] 	server/main.lua:71: in upvalue 'handler'
[  78763031] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78763031] stack traceback:
[  78763046] 	[C]: in function 'error'
[  78763046] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78763062] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78773031] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78773046] stack traceback:
[  78773062] 	server/main.lua:71: in upvalue 'handler'
[  78773062] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78773062] stack traceback:
[  78773078] 	[C]: in function 'error'
[  78773078] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78773093] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78782125] Error running system event handling function for resource esx_license: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:13: attempt to index a nil value (local 'xPlayer')
[  78782125] stack traceback:
[  78782140] 	server/main.lua:13: in function 'AddLicense'
[  78782140] 	server/main.lua:168: in upvalue 'handler'
[  78782156] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78782156] stack traceback:
[  78782171] 	[C]: in function 'error'
[  78782171] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78782187] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78783015] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78783031] stack traceback:
[  78783031] 	server/main.lua:71: in upvalue 'handler'
[  78783046] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78783046] stack traceback:
[  78783062] 	[C]: in function 'error'
[  78783062] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78783078] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78783812] Sending heartbeat to live-internal.fivem.net:30110
[  78793046] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78793062] stack traceback:
[  78793062] 	server/main.lua:71: in upvalue 'handler'
[  78793078] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78793078] stack traceback:
[  78793093] 	[C]: in function 'error'
[  78793093] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78793109] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78803046] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78803046] stack traceback:
[  78803062] 	server/main.lua:71: in upvalue 'handler'
[  78803062] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78803078] stack traceback:
[  78803078] 	[C]: in function 'error'
[  78803093] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78803093] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78813078] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78813078] stack traceback:
[  78813093] 	server/main.lua:71: in upvalue 'handler'
[  78813093] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78813109] stack traceback:
[  78813109] 	[C]: in function 'error'
[  78813125] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78813125] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78816890] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:557: attempt to index a nil value (local 'xPlayer')
[  78816890] stack traceback:
[  78816906] 	server/main.lua:557: in field '?'
[  78816906] 	server/functions.lua:48: in field 'TriggerServerCallback'
[  78816921] 	server/common.lua:73: in upvalue 'handler'
[  78816921] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78816937] stack traceback:
[  78816937] 	[C]: in function 'error'
[  78816953] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78816953] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78823109] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78823125] stack traceback:
[  78823140] 	server/main.lua:71: in upvalue 'handler'
[  78823140] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78823156] stack traceback:
[  78823171] 	[C]: in function 'error'
[  78823171] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78823187] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78833093] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78833109] stack traceback:
[  78833109] 	server/main.lua:71: in upvalue 'handler'
[  78833125] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78833125] stack traceback:
[  78833140] 	[C]: in function 'error'
[  78833140] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78833156] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78843140] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78843140] stack traceback:
[  78843156] 	server/main.lua:71: in upvalue 'handler'
[  78843156] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78843171] stack traceback:
[  78843171] 	[C]: in function 'error'
[  78843171] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78843187] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78853125] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78853125] stack traceback:
[  78853140] 	server/main.lua:71: in upvalue 'handler'
[  78853140] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78853156] stack traceback:
[  78853156] 	[C]: in function 'error'
[  78853171] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78853171] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78863156] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78863156] stack traceback:
[  78863171] 	server/main.lua:71: in upvalue 'handler'
[  78863171] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78863187] stack traceback:
[  78863187] 	[C]: in function 'error'
[  78863187] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78863203] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78873187] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78873203] stack traceback:
[  78873203] 	server/main.lua:71: in upvalue 'handler'
[  78873218] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78873218] stack traceback:
[  78873234] 	[C]: in function 'error'
[  78873234] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78873250] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78883171] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78883187] stack traceback:
[  78883187] 	server/main.lua:71: in upvalue 'handler'
[  78883203] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78883203] stack traceback:
[  78883218] 	[C]: in function 'error'
[  78883218] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78883218] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78893171] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78893171] stack traceback:
[  78893187] 	server/main.lua:71: in upvalue 'handler'
[  78893187] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78893203] stack traceback:
[  78893203] 	[C]: in function 'error'
[  78893218] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78893218] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78903203] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78903203] stack traceback:
[  78903218] 	server/main.lua:71: in upvalue 'handler'
[  78903218] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78903234] stack traceback:
[  78903234] 	[C]: in function 'error'
[  78903250] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78903250] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[  78913281] Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
[  78913281] stack traceback:
[  78913296] 	server/main.lua:71: in upvalue 'handler'
[  78913296] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  78913312] stack traceback:
[  78913312] 	[C]: in function 'error'
[  78913328] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  78913328] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by RomainLanz** [comment]
Hey @funzik! 👋 

Have you downloaded the release or the code directly?

**Comment by funzik** [comment]
yes i download the latest, here : https://github.com/ESX-Org/esx_status and click "clone or download" and "download zip"

**Comment by RomainLanz** [comment]
This aren't the latest stable release, those are dev release, please, update your resource with the release tabs.

**Comment by ForthtuN** [comment]
As ^ said, where is the latest stable then?

**Comment by Lupins** [comment]
The last release has the same problem.

**Comment by MagnanQC** [comment]
Yes, we have the same things...

**Comment by ElPumpo** [comment]
I've pushed an update which should fix the bug where the script tries to set a status for unknown players. Closing for now.
