### ISSUE TITLE
(local Xplayer) on startup

### ISSUE THREAD

**Issue by chinduwho** [ESX-Org/esx_status#25]
Error loading script server/main.lua in resource esx_status: @esx_status/server/main.lua:79: attempt to index a boolean value (local 'xPlayer')
stack traceback:
        @esx_status/server/main.lua:79: in function 'SaveData'
        @esx_status/server/main.lua:94: in main chunk
Failed to load script server/main.lua.

Adding a if xPlayer ~= nil then 
does nothing.

**Comment by RoJea32** [comment]
@ElPumpo @indilo53 @nearbyplayer @renaiku @chinduwho Hello, I have the same issue, the xPlayer things is a null value, it works instantly after restarting a script. What's the problem?
![error](https://user-images.githubusercontent.com/57993332/69240221-acced680-0ba4-11ea-852d-3a5863d57075.png)

**Comment by nearbyplayer** [comment]
Why would you ping everyone? It’s un-needed and quite annoying, I don’t need an email from Github because you didn’t feel like looking through past solutions on the Discord. If you need help and don’t have a bug report ask on the Discord, otherwise you’ll likely be ignored.

**Comment by RoJea32** [comment]
> Why would you ping everyone? It’s un-needed and quite annoying, I don’t need an email from Github because you didn’t feel like looking through past solutions on the Discord. If you need help and don’t have a bug report ask on the Discord, otherwise you’ll likely be ignored.

I am sorry for that. Really, I didn't know about that. But I have a question, what Discord server should I look up to? I asked this on Fivem Server today, and the community responded, they don't help with resources, instead I should ask in Github, so I did that :/

**Comment by nearbyplayer** [comment]
The ESX official discord.
