### ISSUE TITLE
Errors :( I

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_status#3]
`Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
stack traceback:
	server/main.lua:71: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
Error running system event handling function for resource esx_status: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
stack traceback:
	server/main.lua:71: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>`

Im using the last version esx_status.

**Comment by b0hlin** [comment]
Have you find have a solution for the issue ?

**Comment by JaroSound** [comment]
Nope. I still have this issue. Sometimes it crash my serwer :(

**Comment by ElPumpo** [comment]
I've pushed an update which should fix the bug where the script tries to set a status for unknown players. Closing for now.
