### ISSUE TITLE
Nothing Happening

### ISSUE THREAD

**Issue by DonKKijotE** [ESX-Org/esx_status#35]
Hello everyone,

I just installed esx_status along esx_basicneeds but nothing seems to be happening. I imported all necessary SQL into my database and started both scripts like this:

ensure esx_status
ensure esx_basicneeds

The thing is, I start the server and get no errors. I connect with my character and I am able to eat bread and drink water from my inventory. However, apparently nothing is going on regarding hunger or thirst.

I saw the [HOWTO] on the README file, but that code is alredy present in client\main.lua .
When I check my database I can see that the STATUS column on the user table only contains [] for the players that have connected to the server.

I look on the server console for any errors on scripts startup but I see nothing there or on the F8 console.

I would like to apologise in case this has already been solved somewhere but believe me I have been looking at the code and browsing on forums, etc but I have no clue what's going on.

Any help will be greatly appreciated,

thanks in advance and have a great day!

**Comment by FBFezz** [comment]
Getting the same thing, do you have the hud showing up?

**Comment by DonKKijotE** [comment]
Hi man, no HUD showing up for me. I guess it won't show up because the thirst and hunger statuses are not being registered properly. I inserted some debug messages to see if the resources where being loaded properly and they are, but the debug message I inserted on the lines of code regarding registerStatus and no message pops up, so I'm guessing that for whatever reason those lines are not getting to be executed... I have messages regarding this on Cfx, esx-framework.org forum and here... Hopefully I will be able to find out what's going on and I'll give any info here in case it's useful :)

**Comment by FBFezz** [comment]
Thank you, ill mess around with the code later and make a pull request if i figure it out

**Comment by FBFezz** [comment]
Fixed it, download this version (it changed 1 line and was broken) 

https://github.com/ESX-Org/esx_status/tree/59c51e6daf425fa76a7922c8cbc65586af821463

**Comment by DonKKijotE** [comment]
Hey man, I went back to the old ESX version and now EVERYTHING is working great.

It's a bit of a hassle but I think you can migrate most of your resources over to the new server with the old ESX in one evening, consider it :)

Have fun and take care!
