### ISSUE TITLE
Big error

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/esx_status#4]
[ERROR] [MySQL] An critical error happens on MySQL for query "UPDATE users SET status = @status WHERE identifier = @identifier {@identifier=steam:11000013264ec89;@status=[{"val":877400,"percent":87.74,"name":"hunger"},{"val":846250,"percent":84.625,"name":"thirst"},{"val":0,"percent":0.0,"name":"drunk"}]}": Value does not fall within the expected range. at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Int32 optionValue) [0x00023] in <7d13762c3f3046279fc4d30c52f

**Comment by ElPumpo** [comment]
Can you reproduce this bug?
