### ISSUE TITLE
Does anyone know how to leave the bars of hunger and thirst of the esx_status, one in front of the other, instead of being one on top of the other?

### ISSUE THREAD

**Issue by italocbanker** [ESX-Org/esx_status#5]
https://forum.fivem.net/t/help-esx-status-bars/96670/

**Comment by ElPumpo** [comment]
The first thing you'll want to change is the div, make it a span. Div always make a newline

**Comment by JaroSound** [comment]
When i change div to span it is not visible anymore.

**Comment by Sopuli86** [comment]
reconnect and it will be visible again
