### ISSUE TITLE
Question: Display of bars #2 !

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/esx_status#9]
**I have been banned from the esx discord for no reason.
I was helping people in the help section as much as I could
I send a email to one of the esx admin and never got an answer so yeah, I have to ask here
So i can't go check the help section, so please, don't close this and help**

Hello, I am wondering how can I play the bar next to each other insted of them being under each one ?
I see in the script that it use span in the html but it's making a new line for every status bar because in app.js they are in div?

What I am trying to do is place the bar under the minimap like this : 1) ------  2) ------

insted of being like this : 
1) -----
2) -----

**Comment by nykroza** [comment]
nevermind, i got it to work

**Comment by KrYpTiiK** [comment]
@nykroza Can you tell me how you got this to work?
